### ISSUE TITLE
Can you explain one constant to me?

### ISSUE THREAD

**Issue by terrythefirst** [fynnfluegge/oreon-engine#50]
first of all, thanks for your generosity by sharing your code and I feel so thankful
I've tried to implement the ocean fft part of your engine using Vulkan Cpp API,and I think in your vulkan ocean fft shader folder, the h0k compute shader 

        //sqrt(Ph(k))/sqrt(2)
	float h0k = clamp(sqrt((constants.amplitude/(magSq*magSq)) *
         pow(dot(normalize(k), normalize(constants.w)), 2.0) * //this one
		exp(-(1.0/(magSq * L_ * L_))) * exp(magSq*
         pow(constants.capillarSupressFactor,2.0)))/ sqrt(2.0), -4000.0, 4000.0);
	
	//sqrt(Ph(-k))/sqrt(2)
	float h0minusk = clamp(sqrt((constants.amplitude/(magSq*magSq)) * 
         pow(dot(normalize(-k), normalize(constants.w)), 2.0)  *//and this one
         exp(-(1.0/(magSq * L_ * L_))) * exp(- 
         magSq*pow(constants.capillarSupressFactor,2.0)))/ sqrt(2.0), -4000.0, 4000.0);

these two "2.0" were wrongly(I supposed，because I dont really know the thesis and math stuff） typed into "4.0"

**Comment by terrythefirst** [comment]
Sorry I dont know how to use these mark tool
float h0k = clamp(sqrt((constants.amplitude/(magSq*magSq)) * pow(dot(normalize(k), normalize(constants.w)), **2.0**)

**Comment by terrythefirst** [comment]
And now I think it's a constant that can be changed depending on what effects you want?
hopefully can you explain it to me?

**Comment by fynnfluegge** [comment]
normalize(constants.w)), 2.0) is the alignment strength of the waves to the wind direction. if you set it to normalize(constants.w)), 4.0) it is more aligned and normalize(constants.w)), 8.0) even more and so on...
There are no other parameters need to be changed accordingly.
But on some NVidia GPUs (GTX 1060, Titan Xp) I had issues with this. Only with normalize(constants.w)), 2.0) I got correct results on these GPUs. I did not found the reason... With Vulkan these errors are solved, so the errors are most likely glsl compiler dependent, because Vulkan uses precompiled SPIR-V files. You need to do reverse engineering on the OpenGL driver to find the reason...
I guess you have a Nvidia GPU, so you have to be satisfied with normalize(constants.w)), 2.0), I can't help you there sorry :/

**Comment by terrythefirst** [comment]
Yes,I‘am testing it on a NVidia CTX970M GPU.And I am very satisfied with the result.
And again,thanks very much for your time @fynnfluegge
